[workspace]

members = [
    "./concurrency/stream",
    "./concurrency/cpubound",
    "./concurrency/cron-job-tokio",
    "./io/file-read",
    "./mem/smart-pointers",
    "./io/http-client",
    "./io/grpc-cli-srv",
    "./utils/logging",
]
