[workspace]

members = [
    "./concurrency/stream",
    "./concurrency/cpubound",
    "./concurrency/cron-job-tokio",
    "./data/iter",
    "./io/file-read",
    "./mem/smart-pointers",
    "./io/http-client",
    "./io/grpc-cli-srv",
    "./services/static-site-generator",
    "./utils/logging",
    "./utils/logging-stdout",
    "./utils/logging-custom",
    "./utils/logging-syslog",
]
